DROP TABLE IF EXISTS POLICY;

CREATE TABLE POLICY (
       ID INT NOT NULL AUTO_INCREMENT
     , POLICY_NAME VARCHAR(60) NOT NULL
     , START_DATE VARCHAR(11)
     , DESCRIPTION VARCHAR(2000)
     , VERSION INT NOT NULL DEFAULT 0
     , PRIMARY KEY (ID)
);